# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Template.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1120, 560)
        self.Img_Frame = QtWidgets.QLabel(Form)
        self.Img_Frame.setGeometry(QtCore.QRect(30, 50, 640, 480))
        self.Img_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Img_Frame.setText("")
        self.Img_Frame.setObjectName("Img_Frame")
        self.Img_RGB_Button = QtWidgets.QRadioButton(Form)
        self.Img_RGB_Button.setGeometry(QtCore.QRect(30, 20, 112, 23))
        self.Img_RGB_Button.setChecked(True)
        self.Img_RGB_Button.setObjectName("Img_RGB_Button")
        self.Img_Depth_Button = QtWidgets.QRadioButton(Form)
        self.Img_Depth_Button.setGeometry(QtCore.QRect(140, 20, 112, 23))
        self.Img_Depth_Button.setObjectName("Img_Depth_Button")
        self.Title_1 = QtWidgets.QLabel(Form)
        self.Title_1.setGeometry(QtCore.QRect(700, 20, 411, 31))
        self.Title_1.setMinimumSize(QtCore.QSize(16, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.Title_1.setFont(font)
        self.Title_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_1.setWordWrap(True)
        self.Title_1.setObjectName("Title_1")
        self.Home_Button = QtWidgets.QPushButton(Form)
        self.Home_Button.setGeometry(QtCore.QRect(700, 464, 90, 60))
        self.Home_Button.setObjectName("Home_Button")
        self.Title_2 = QtWidgets.QLabel(Form)
        self.Title_2.setGeometry(QtCore.QRect(700, 240, 411, 21))
        self.Title_2.setMinimumSize(QtCore.QSize(16, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.Title_2.setFont(font)
        self.Title_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_2.setWordWrap(True)
        self.Title_2.setObjectName("Title_2")
        self.XY_Title = QtWidgets.QLabel(Form)
        self.XY_Title.setGeometry(QtCore.QRect(700, 70, 190, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.XY_Title.setFont(font)
        self.XY_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.XY_Title.setObjectName("XY_Title")
        self.XY_Val = QtWidgets.QLabel(Form)
        self.XY_Val.setGeometry(QtCore.QRect(700, 110, 190, 30))
        self.XY_Val.setFrameShape(QtWidgets.QFrame.Box)
        self.XY_Val.setText("")
        self.XY_Val.setAlignment(QtCore.Qt.AlignCenter)
        self.XY_Val.setObjectName("XY_Val")
        self.XY_X_Title = QtWidgets.QLabel(Form)
        self.XY_X_Title.setGeometry(QtCore.QRect(700, 150, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XY_X_Title.sizePolicy().hasHeightForWidth())
        self.XY_X_Title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.XY_X_Title.setFont(font)
        self.XY_X_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.XY_X_Title.setObjectName("XY_X_Title")
        self.XY_X_SpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.XY_X_SpinBox.setGeometry(QtCore.QRect(730, 150, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XY_X_SpinBox.sizePolicy().hasHeightForWidth())
        self.XY_X_SpinBox.setSizePolicy(sizePolicy)
        self.XY_X_SpinBox.setObjectName("XY_X_SpinBox")
        self.XY_Y_SpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.XY_Y_SpinBox.setGeometry(QtCore.QRect(730, 180, 100, 30))
        self.XY_Y_SpinBox.setObjectName("XY_Y_SpinBox")
        self.XY_Button = QtWidgets.QPushButton(Form)
        self.XY_Button.setGeometry(QtCore.QRect(839, 150, 51, 60))
        self.XY_Button.setObjectName("XY_Button")
        self.XY_Y_Title = QtWidgets.QLabel(Form)
        self.XY_Y_Title.setGeometry(QtCore.QRect(700, 180, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XY_Y_Title.sizePolicy().hasHeightForWidth())
        self.XY_Y_Title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.XY_Y_Title.setFont(font)
        self.XY_Y_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.XY_Y_Title.setObjectName("XY_Y_Title")
        self.Grip_Open = QtWidgets.QPushButton(Form)
        self.Grip_Open.setGeometry(QtCore.QRect(1018, 270, 90, 60))
        self.Grip_Open.setObjectName("Grip_Open")
        self.Grip_Close = QtWidgets.QPushButton(Form)
        self.Grip_Close.setGeometry(QtCore.QRect(910, 270, 90, 60))
        self.Grip_Close.setObjectName("Grip_Close")
        self.Z_Title = QtWidgets.QLabel(Form)
        self.Z_Title.setGeometry(QtCore.QRect(910, 70, 190, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Z_Title.setFont(font)
        self.Z_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Z_Title.setObjectName("Z_Title")
        self.Z_Val = QtWidgets.QLabel(Form)
        self.Z_Val.setGeometry(QtCore.QRect(910, 110, 190, 30))
        self.Z_Val.setFrameShape(QtWidgets.QFrame.Box)
        self.Z_Val.setText("")
        self.Z_Val.setAlignment(QtCore.Qt.AlignCenter)
        self.Z_Val.setObjectName("Z_Val")
        self.Z_SpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.Z_SpinBox.setGeometry(QtCore.QRect(910, 150, 190, 30))
        self.Z_SpinBox.setObjectName("Z_SpinBox")
        self.Z_Button = QtWidgets.QPushButton(Form)
        self.Z_Button.setGeometry(QtCore.QRect(910, 180, 190, 30))
        self.Z_Button.setObjectName("Z_Button")
        self.Grip_Val = QtWidgets.QLabel(Form)
        self.Grip_Val.setGeometry(QtCore.QRect(700, 270, 190, 30))
        self.Grip_Val.setFrameShape(QtWidgets.QFrame.Box)
        self.Grip_Val.setText("")
        self.Grip_Val.setAlignment(QtCore.Qt.AlignCenter)
        self.Grip_Val.setObjectName("Grip_Val")
        self.Grip_SpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.Grip_SpinBox.setGeometry(QtCore.QRect(700, 300, 90, 30))
        self.Grip_SpinBox.setObjectName("Grip_SpinBox")
        self.Grip_Button = QtWidgets.QPushButton(Form)
        self.Grip_Button.setGeometry(QtCore.QRect(800, 300, 90, 30))
        self.Grip_Button.setObjectName("Grip_Button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Img_RGB_Button.setText(_translate("Form", "RGB Image"))
        self.Img_Depth_Button.setText(_translate("Form", "Depth Image"))
        self.Title_1.setText(_translate("Form", "Robot arm controls"))
        self.Home_Button.setText(_translate("Form", "Start /\n"
"Go to home"))
        self.Title_2.setText(_translate("Form", "Gripper controls"))
        self.XY_Title.setText(_translate("Form", "X,Y-Axis"))
        self.XY_X_Title.setText(_translate("Form", "X"))
        self.XY_Button.setText(_translate("Form", "Set"))
        self.XY_Y_Title.setText(_translate("Form", "Y"))
        self.Grip_Open.setText(_translate("Form", "Open"))
        self.Grip_Close.setText(_translate("Form", "Close"))
        self.Z_Title.setText(_translate("Form", "Z-Axis"))
        self.Z_Button.setText(_translate("Form", "Set"))
        self.Grip_Button.setText(_translate("Form", "Set"))
