// Generated by gencpp from file arm/dynamixel_srv.msg
// DO NOT EDIT!


#ifndef ARM_MESSAGE_DYNAMIXEL_SRV_H
#define ARM_MESSAGE_DYNAMIXEL_SRV_H

#include <ros/service_traits.h>


#include <arm/dynamixel_srvRequest.h>
#include <arm/dynamixel_srvResponse.h>


namespace arm
{

struct dynamixel_srv
{

typedef dynamixel_srvRequest Request;
typedef dynamixel_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct dynamixel_srv
} // namespace arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm::dynamixel_srv > {
  static const char* value()
  {
    return "e914a2ad5395f6f66880d5aed68f5700";
  }

  static const char* value(const ::arm::dynamixel_srv&) { return value(); }
};

template<>
struct DataType< ::arm::dynamixel_srv > {
  static const char* value()
  {
    return "arm/dynamixel_srv";
  }

  static const char* value(const ::arm::dynamixel_srv&) { return value(); }
};


// service_traits::MD5Sum< ::arm::dynamixel_srvRequest> should match
// service_traits::MD5Sum< ::arm::dynamixel_srv >
template<>
struct MD5Sum< ::arm::dynamixel_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm::dynamixel_srv >::value();
  }
  static const char* value(const ::arm::dynamixel_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm::dynamixel_srvRequest> should match
// service_traits::DataType< ::arm::dynamixel_srv >
template<>
struct DataType< ::arm::dynamixel_srvRequest>
{
  static const char* value()
  {
    return DataType< ::arm::dynamixel_srv >::value();
  }
  static const char* value(const ::arm::dynamixel_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm::dynamixel_srvResponse> should match
// service_traits::MD5Sum< ::arm::dynamixel_srv >
template<>
struct MD5Sum< ::arm::dynamixel_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm::dynamixel_srv >::value();
  }
  static const char* value(const ::arm::dynamixel_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm::dynamixel_srvResponse> should match
// service_traits::DataType< ::arm::dynamixel_srv >
template<>
struct DataType< ::arm::dynamixel_srvResponse>
{
  static const char* value()
  {
    return DataType< ::arm::dynamixel_srv >::value();
  }
  static const char* value(const ::arm::dynamixel_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_MESSAGE_DYNAMIXEL_SRV_H
