// Generated by gencpp from file arm/Float_srv.msg
// DO NOT EDIT!


#ifndef ARM_MESSAGE_FLOAT_SRV_H
#define ARM_MESSAGE_FLOAT_SRV_H

#include <ros/service_traits.h>


#include <arm/Float_srvRequest.h>
#include <arm/Float_srvResponse.h>


namespace arm
{

struct Float_srv
{

typedef Float_srvRequest Request;
typedef Float_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Float_srv
} // namespace arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm::Float_srv > {
  static const char* value()
  {
    return "e914a2ad5395f6f66880d5aed68f5700";
  }

  static const char* value(const ::arm::Float_srv&) { return value(); }
};

template<>
struct DataType< ::arm::Float_srv > {
  static const char* value()
  {
    return "arm/Float_srv";
  }

  static const char* value(const ::arm::Float_srv&) { return value(); }
};


// service_traits::MD5Sum< ::arm::Float_srvRequest> should match
// service_traits::MD5Sum< ::arm::Float_srv >
template<>
struct MD5Sum< ::arm::Float_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm::Float_srv >::value();
  }
  static const char* value(const ::arm::Float_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm::Float_srvRequest> should match
// service_traits::DataType< ::arm::Float_srv >
template<>
struct DataType< ::arm::Float_srvRequest>
{
  static const char* value()
  {
    return DataType< ::arm::Float_srv >::value();
  }
  static const char* value(const ::arm::Float_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm::Float_srvResponse> should match
// service_traits::MD5Sum< ::arm::Float_srv >
template<>
struct MD5Sum< ::arm::Float_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm::Float_srv >::value();
  }
  static const char* value(const ::arm::Float_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm::Float_srvResponse> should match
// service_traits::DataType< ::arm::Float_srv >
template<>
struct DataType< ::arm::Float_srvResponse>
{
  static const char* value()
  {
    return DataType< ::arm::Float_srv >::value();
  }
  static const char* value(const ::arm::Float_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_MESSAGE_FLOAT_SRV_H
