// Generated by gencpp from file arm/stepper_srvRequest.msg
// DO NOT EDIT!


#ifndef ARM_MESSAGE_STEPPER_SRVREQUEST_H
#define ARM_MESSAGE_STEPPER_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm
{
template <class ContainerAllocator>
struct stepper_srvRequest_
{
  typedef stepper_srvRequest_<ContainerAllocator> Type;

  stepper_srvRequest_()
    : data1(0.0)
    , data2(0.0)  {
    }
  stepper_srvRequest_(const ContainerAllocator& _alloc)
    : data1(0.0)
    , data2(0.0)  {
  (void)_alloc;
    }



   typedef double _data1_type;
  _data1_type data1;

   typedef double _data2_type;
  _data2_type data2;





  typedef boost::shared_ptr< ::arm::stepper_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm::stepper_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct stepper_srvRequest_

typedef ::arm::stepper_srvRequest_<std::allocator<void> > stepper_srvRequest;

typedef boost::shared_ptr< ::arm::stepper_srvRequest > stepper_srvRequestPtr;
typedef boost::shared_ptr< ::arm::stepper_srvRequest const> stepper_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm::stepper_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm::stepper_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm::stepper_srvRequest_<ContainerAllocator1> & lhs, const ::arm::stepper_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data1 == rhs.data1 &&
    lhs.data2 == rhs.data2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm::stepper_srvRequest_<ContainerAllocator1> & lhs, const ::arm::stepper_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm::stepper_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::stepper_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm::stepper_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm::stepper_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::stepper_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::stepper_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm::stepper_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc8a80b6983735ea28977d1f8b7b5f10";
  }

  static const char* value(const ::arm::stepper_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc8a80b6983735eaULL;
  static const uint64_t static_value2 = 0x28977d1f8b7b5f10ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm::stepper_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm/stepper_srvRequest";
  }

  static const char* value(const ::arm::stepper_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm::stepper_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 data1\n"
"float64 data2\n"
;
  }

  static const char* value(const ::arm::stepper_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm::stepper_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data1);
      stream.next(m.data2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stepper_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm::stepper_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm::stepper_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "data1: ";
    Printer<double>::stream(s, indent + "  ", v.data1);
    s << indent << "data2: ";
    Printer<double>::stream(s, indent + "  ", v.data2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_MESSAGE_STEPPER_SRVREQUEST_H
