(cl:defpackage arm-srv
  (:use )
  (:export
   "DYNAMIXEL_SRV"
   "<DYNAMIXEL_SRV-REQUEST>"
   "DYNAMIXEL_SRV-REQUEST"
   "<DYNAMIXEL_SRV-RESPONSE>"
   "DYNAMIXEL_SRV-RESPONSE"
   "STEPPER_SRV"
   "<STEPPER_SRV-REQUEST>"
   "STEPPER_SRV-REQUEST"
   "<STEPPER_SRV-RESPONSE>"
   "STEPPER_SRV-RESPONSE"
  ))

